import Head from "next/head";

import Header from "./header";
import Footer from "./footer";

const Layout = ({ children, metaTitle, metaDescription }) => {
   return (
      <div>
         <Head>
            <title>{`${metaTitle} - Notes`}</title>
            <meta name="description" content={metaDescription || "Generated by create next app"} />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <Header />
         {children}
         <Footer />
      </div>
   )
}

export default Layout;