import Head from "next/head";

import { Box, Container, Flex } from "@chakra-ui/react";

import Header from "./header";
import Footer from "./footer";

const Layout = ({ children, metaTitle='Sanberdaly', metaDescription='Sanberdaly', width }) => {

   return (
      <div>
         <Head>
            <title>{`${metaTitle} - Notes`}</title>
            <meta name="description" content={metaDescription || "Generated by create next app"} />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <Container width="full" centerContent>
            <Flex direction="column" bg="whiteAlpha.900" width={width}>
               <Header />
               <Box height="85vh" overflow="scroll" padding="2" position="relative">
                  {children}
               </Box>
               
               <Footer />
            </Flex>
         </Container>
         
      </div>
   )
}

export default Layout;